### ISSUE TITLE
[NavigationCodelab]Tests doesn't work

### ISSUE THREAD

**Issue by NARUTONBM** [googlecodelabs/android-compose-codelabs#193]
Description
I create the same `RallyNavHostTest.kt` as the [Compose Navigation Codelab](https://developer.android.google.cn/codelabs/jetpack-compose-navigation?continue=https%3A%2F%2Fdeveloper.android.google.cn%2Fcourses%2Fpathways%2Fcompose%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fjetpack-compose-navigation#6). All those tests never pass.

Steps to Reproduce
Just try the code in [RallyNavHostTest.kt](https://github.com/googlecodelabs/android-compose-codelabs/blob/end/NavigationCodelab/app/src/androidTest/java/com/example/compose/rally/RallyNavHostTest.kt) in branch `end`

Expected Results
Test passes when I hit the run button

Actual Results
Test fails after 45 seconds when run in an application module with the following stacktrace:
```java
--------- beginning of main
08-15 16:02:04.725 10217  7167  7211 W Settings: Setting always_finish_activities has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
--------- beginning of system
08-15 16:02:04.731 10217  7167  7211 I Timeline: Timeline: Activity_launch_request time:420553368
08-15 16:02:04.733  1000  1300  2476 I ActivityTaskManager: START u0 {act=android.app.action.CHECK_ALLOW_START_ACTIVITY flg=0x800000 pkg=com.miui.securitycenter cmp=com.miui.securitycenter/com.miui.wakepath.ui.ConfirmStartActivity (has extras)} from uid 10217
08-15 16:02:04.733  1000  1300  2476 D ActivityTaskManagerServiceInjector: MIUILOG- Permission Denied Activity : Intent { act=android.app.action.CHECK_ALLOW_START_ACTIVITY flg=0x800000 pkg=com.miui.securitycenter cmp=com.miui.securitycenter/com.miui.wakepath.ui.ConfirmStartActivity (has extras) } pkg : com.demo.composenavi uid : 10217 tuid : 10084
08-15 16:02:04.734  1000  1300  2476 D MiuiMultiWindowAdapter: MiuiMultiWindowAdapter::getFreeformBlackList::sSmallWindowBlackList = [com.miui.securitycenter, com.miui.weather2, com.miui.miservice, com.android.calendar, com.xiaomi.calendar, com.android.contacts, com.miui.mishare.connectivity, com.android.settings, com.android.printspooler, com.miui.backup, com.miui.huanji, com.miui.calculator, com.android.deskclock, com.android.thememanager, com.mfashiongallery.emag, com.miui.virtualsim, com.miui.smarttravel, com.mi.health, com.android.camera, com.lbe.security.miui, com.miui.cleanmaster, com.miui.newhome, com.miui.voiceassist, com.android.phone, com.miui.yellowpage, com.android.updater, com.miui.tsmclient, com.miui.securitycore, com.xiaomi.account, com.xiaomi.shop, com.xiaomi.smarthome, com.mipay.wallet, com.xiaomi.youpin, com.xiaomi.hm.health, com.miui.bugreport, com.xiaomi.mibrain.speech, com.xiaomi.mimoji, com.xiaomi.scanner, com.duokan.phone.remotecontroller, com.miui.hybrid, com.android.incallui, com.miui.video, com.miui.videoplayer, com.miui.player, com.miui.fm, com.miui.packageinstaller, com.mi.android.globallauncher, com.mi.android.globallauncher-poco, com.google.android.dialer, com.google.android.apps.magazines, com.miui.compass, com.miui.greenguard, com.kiteguard, com.google.android.apps.prodcasts, com.google.ar.lens, com.xiangkan.android, com.android.bankabc, com.sohu.inputmethod.sogou, com.tencent.mtt, com.shyz.toutiao, com.netease.mc.mi, com.outfit7.talkingtomgoldrun.mi, com.doudz.mi, com.wepie.snake.new.mi, cn.jj, com.standddz002.mi, com.miHoYo.bh3.mi, com.qqgame.hlddz, com.happyelements.AndroidAnimal, com.minitech.miniworld.TMobile.mi, com.mfp.jelly.xiaomi, com.lilithgames.afk.mi, com.tencent.peng, com.teenpatti.hd.gold, blockpuzzle.jewelgames.jewelslegend, com.playgendary.tanks, com.chillingo.robberybobfree.android.row, com.episodeinteractive.android.catalog, com.playrix.township, com.ansangha.drdriving, com.google.android.youtube, com.gbits.atm.mi, com.tencent.tetris, com.sukhavati.gotoplaying.bubble.BubbleShooter.mint, com.block.puzzle.game.hippo.mi, com.youzu.bs.mi, com.appsomniacs.da2, com.miHoYo.Yuanshen, com.baidu.BaiduMap, com.google.android.googlequicksearchbox]
08-15 16:02:04.971  1000  1300  1459 E WifiVendorHal: getWifiLinkLayerStats_1_3_Internal(l.927) failed {.code = ERROR_NOT_SUPPORTED, .description = }
08-15 16:02:04.974  1047   678  8850 E lsc_nvram: [do_mkdir] fail to mkdir [/sdcard/shading_otp]: 13[Permission denied] (do_mkdir){#65:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/isp_40/lsc_mgr/LscUtil.h}
08-15 16:02:04.969  1047   678   678 W camerahalserver: type=1400 audit(0.0:859303): avc: denied { search } for name="0" dev="mmcblk0p46" ino=188421 scontext=u:r:mtk_hal_camera:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=0
08-15 16:02:04.969  1047   678   678 W camerahalserver: type=1400 audit(0.0:859304): avc: denied { search } for name="0" dev="mmcblk0p46" ino=188421 scontext=u:r:mtk_hal_camera:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=0
08-15 16:02:05.000  1000  1540  1540 D KeyguardUpdateMonitor: handleTimeUpdate
08-15 16:02:05.018  1000   549  1277 I BufferQueueProducer: [StatusBar#0](this:0x78e4074800,id:4,api:1,p:1540,c:549) queueBuffer: fps=0.66 dur=3031.75 max=3019.92 min=11.83
08-15 16:02:05.033  1000   509   509 I hwcomposer: [HWCDisplay] [Display_0 (type:1)] fps:0.658662,dur:3036.46,max:3020.04,min:16.42  
08-15 16:02:05.039  1000  1300  1432 W SensorService: Dropping 1 cached events (984/984) to save 1/1 new events. 6 events previously dropped
08-15 16:02:05.373  1000   689   689 D AALLightSensor: newLux = 1705, [1141, 1141] -> 1705
08-15 16:02:05.974  1047   678  8850 E lsc_nvram: [do_mkdir] fail to mkdir [/sdcard/shading_otp]: 13[Permission denied] (do_mkdir){#65:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/isp_40/lsc_mgr/LscUtil.h}
08-15 16:02:05.969  1047   678   678 W camerahalserver: type=1400 audit(0.0:859305): avc: denied { search } for name="0" dev="mmcblk0p46" ino=188421 scontext=u:r:mtk_hal_camera:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=0
08-15 16:02:05.969  1047   678   678 W camerahalserver: type=1400 audit(0.0:859306): avc: denied { search } for name="0" dev="mmcblk0p46" ino=188421 scontext=u:r:mtk_hal_camera:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=0
08-15 16:02:06.975  1047   678  8850 E lsc_nvram: [do_mkdir] fail to mkdir [/sdcard/shading_otp]: 13[Permission denied] (do_mkdir){#65:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/isp_40/lsc_mgr/LscUtil.h}
08-15 16:02:06.973  1047   678   678 W camerahalserver: type=1400 audit(0.0:859307): avc: denied { search } for name="0" dev="mmcblk0p46" ino=188421 scontext=u:r:mtk_hal_camera:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=0
08-15 16:02:06.973  1047   678   678 W camerahalserver: type=1400 audit(0.0:859308): avc: denied { search } for name="0" dev="mmcblk0p46" ino=188421 scontext=u:r:mtk_hal_camera:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=0
08-15 16:02:07.373  1000  1300  1432 W SensorService: Dropping 1 cached events (984/984) to save 1/1 new events. 6 events previously dropped
08-15 16:02:07.976  1047   678  8850 E lsc_nvram: [do_mkdir] fail to mkdir [/sdcard/shading_otp]: 13[Permission denied] (do_mkdir){#65:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/isp_40/lsc_mgr/LscUtil.h}
08-15 16:02:07.973  1047   678   678 W camerahalserver: type=1400 audit(0.0:859309): avc: denied { search } for name="0" dev="mmcblk0p46" ino=188421 scontext=u:r:mtk_hal_camera:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=0
08-15 16:02:07.973  1047   678   678 W camerahalserver: type=1400 audit(0.0:859310): avc: denied { search } for name="0" dev="mmcblk0p46" ino=188421 scontext=u:r:mtk_hal_camera:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=0
08-15 16:02:07.988  1000  1300  1459 E WifiVendorHal: getWifiLinkLayerStats_1_3_Internal(l.927) failed {.code = ERROR_NOT_SUPPORTED, .description = }
08-15 16:02:08.484 10084 23733 23733 I PowerHalWrapper: phwperfLockAcq
08-15 16:02:08.485 10084 23733 23733 I mtkperf_client: [perf_lock_acq] hdl:3787, dur:120, num:8
08-15 16:02:08.481 10084 23733 23733 W com.miui.home: type=1400 audit(0.0:859311): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5141 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:sysfs_boot_mode:s0 tclass=file permissive=0
08-15 16:02:08.485 10084 23733 23733 I mtkperf_client: perf_lock_acq, hdl:3787, dur:120, tid:23733
08-15 16:02:08.486  1000   523   571 I mtkpower@1.0-impl: perfLockAcquire hdl:3787, duration:120, reserved:23733
08-15 16:02:08.481  1000   523   523 W mtkPowerManager: type=1400 audit(0.0:859312): avc: denied { getattr } for path="/proc/23733" dev="proc" ino=1920036 scontext=u:r:mtk_hal_power:s0 tcontext=u:r:platform_app:s0:c512,c768 tclass=dir permissive=0
08-15 16:02:08.481  1000   523   523 W mtkPowerManager: type=1400 audit(0.0:859313): avc: denied { search } for name="23733" dev="proc" ino=1920036 scontext=u:r:mtk_hal_power:s0 tcontext=u:r:platform_app:s0:c512,c768 tclass=dir permissive=0
08-15 16:02:08.486  1000   523   570 I powerd  : [powerd_req] POWER_MSG_PERF_LOCK_ACQ: hdl:3787, duration:120
08-15 16:02:08.487  1000   523   570 E libPowerHal: Could not open '/proc/23733/comm'
08-15 16:02:08.487  1000   523   570 E libPowerHal: error : 13, Permission denied
08-15 16:02:08.487  1000   523   570 I libPowerHal: perfLockAcq hdl:3787 pid:23733 duration:120 pid_exist:0 => new_hdl:3791
08-15 16:02:08.487  1000   523   570 I libPowerHal: 124: set gpu level: 0
08-15 16:02:08.487  1000   523   570 I libPowerHal: 124: set gpu level max: 0
08-15 16:02:08.487  1000   523   570 I libPowerHal: 124: cpu_ctrl set freq: 1600000 -1 1800000 -1
08-15 16:02:08.487  1000   523   570 I powerd  : [powerd_req] POWER_MSG_PERF_LOCK_ACQ: return hdl:3791
08-15 16:02:08.488 10084 23733 23733 I mtkperf_client: ret_hdl:3791
08-15 16:02:08.488 10084 23733 23733 D EventBus: No subscribers registered for event class com.miui.home.launcher.common.messages.EndSpringAnimatorMessage
08-15 16:02:08.488 10084 23733 23733 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
08-15 16:02:08.489 10084 23733 23733 D FeedSwipeController: touchState : 0 scrolling : false normalEditing : false WidgetThumbnailViewShowing : false UninstallDialogShowing : false isMinusScreenShowing: false
08-15 16:02:08.489 10084 23733 23733 D FeedSwipeController: ACTION_DOWN-> directions To Detect Scroll: 1=POSITIVE 2=NEGATIVE 3=BOTH 1
08-15 16:02:08.489 10084 23733 23733 D Launcher.Workspace: Workspace touch down
08-15 16:02:08.489 10084 23733 23733 D ScreenView_Workspace: onIntercept:0.0
08-15 16:02:08.489 10084 23733 23733 D ScreenView_Workspace: not intercept
08-15 16:02:08.504  1000   549  1277 I BufferQueueProducer: [com.miui.home/com.miui.home.launcher.Launcher#0](this:0x78e4
java.lang.AssertionError: Activity never becomes requested state "[STARTED, DESTROYED, CREATED, RESUMED]" (last lifecycle transition = "PRE_ON_CREATE")
	at androidx.test.core.app.ActivityScenario.waitForActivityToBecomeAnyOf(ActivityScenario.java:338)
	at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:272)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:195)
	at androidx.test.ext.junit.rules.ActivityScenarioRule.lambda$new$0$ActivityScenarioRule(ActivityScenarioRule.java:70)
	at androidx.test.ext.junit.rules.ActivityScenarioRule$$Lambda$0.get(ActivityScenarioRule.java:70)
	at androidx.test.ext.junit.rules.ActivityScenarioRule.before(ActivityScenarioRule.java:103)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidComposeStatement.evaluateInner(AndroidComposeTestRule.android.kt:361)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidComposeStatement.evaluate(AndroidComposeTestRule.android.kt:350)
	at androidx.compose.ui.test.junit4.android.EspressoLink$getStatementFor$1.evaluate(EspressoLink.android.kt:63)
	at androidx.compose.ui.test.junit4.IdlingResourceRegistry$getStatementFor$1.evaluate(IdlingResourceRegistry.jvm.kt:160)
	at androidx.compose.ui.test.junit4.android.ComposeRootRegistry$getStatementFor$1.evaluate(ComposeRootRegistry.android.kt:150)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2198)
```

AndroidX Test and Android OS Versions
```gradle

    junit_version = '4.13.2'
    junit_ext_version = '1.1.3'
    truth_version = '1.0.1'
    espresso_version = '3.4.0'
    compose_version = '1.0.1'
    coreTestingVersion = '2.1.0'
    coroutines_test_version = '1.5.0'

    testImplementation "junit:junit:$junit_version"
    testImplementation "com.google.truth:truth:$truth_version"
    androidTestImplementation "androidx.test.ext:junit:$junit_ext_version"
    androidTestImplementation "androidx.test.espresso:espresso-core:$espresso_version"
    androidTestImplementation "androidx.test.espresso:espresso-contrib:$espresso_version"
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
    androidTestImplementation "androidx.arch.core:core-testing:$coreTestingVersion"
    androidTestImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutines_test_version"
```

Run on a RedMI 9 running MIUI 12.0.4 based on Android 10.

**Comment by NARUTONBM** [comment]
I fix this by replacing
```kotlin
    @get:Rule
    val composeTestRule = createAndroidComposeRule(RallyActivity::class.java)
```
with
```kotlin
    @get:Rule
    val composeTestRule = createComposeRule()
```
and all those tests work fine.
